# Generated by Django 3.2.4 on 2021-06-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(default=True),
        ),
    ]
